import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'
import type { SearchResultItem } from '@features/search/types/searchTypes';

export const SEARCH_API = `https://potterapi-fedeperin.vercel.app/en/characters/`;

/**
 */
export const searchApiSlice = createApi({
    reducerPath: 'searchApi',
    baseQuery: fetchBaseQuery({ baseUrl: SEARCH_API }),
    endpoints: (builder) => ({

        getSearchResults: builder.query<SearchResultItem[], string>({
            query: (searchTerm) => `?&search=${searchTerm}`
        })
    }),
});

// Hooks are automatically generated by redux toolkit based on the endpoint names
export const { useGetSearchResultsQuery } = searchApiSlice;